clc; clear; close all;

% -------- data (current example: 113016) --------
Img = imread('113016.jpg');
B = load('class113016.mat'); B = B.class113016;
class = double(reshape(B,[size(B,1)*size(B,2) 1]));
k = size(unique(class),1);

% -------- feature extraction --------
fprintf('Feature extraction...\n');
X = FeatureExtractor(Img);
[N,d]=size(X);

% -------- parameters (use the recommended for 113016 from your comment) --------
beta_z = -10;
p_init = 0;
p_max  = 0.5;
p_step = 0.01;
t_max  = 100;
beta_memory = 0.3;
Restarts = 5;
fuzzy_degree = 2;

% group weights v: 0.1 / 0.7 / 0.2 for (1:3)/(4:6)/(7:8)
v = ones(1,d);
v(1,1:3)=0.1; v(1,4:6)=0.7; v(1,7:8)=0.2;
G = [1 1 1 2 2 2 3 3];

% landa
oo = 0.0001;
landa = oo./var(X);
TF = find(isinf(landa)==1);
if ~isempty(TF)
    for i=1:size(TF,2), landa(1,TF(i))=nan; end
    aa=max(landa);
    for i=1:size(TF,2), landa(1,TF(i))=aa+1; end
end

% -------- ablation configs --------
variants = {
 'Full', struct('learnW',true,'learnZ',true,'useMemory',true,'adaptiveP',true,'useV',true,'useKernel',true);
 'w/o learnW', struct('learnW',false,'learnZ',true,'useMemory',true,'adaptiveP',true,'useV',true,'useKernel',true);
 'w/o learnZ', struct('learnW',true,'learnZ',false,'useMemory',true,'adaptiveP',true,'useV',true,'useKernel',true);
 'w/o memory', struct('learnW',true,'learnZ',true,'useMemory',false,'adaptiveP',true,'useV',true,'useKernel',true);
 'w/o adaptive p', struct('learnW',true,'learnZ',true,'useMemory',true,'adaptiveP',false,'useV',true,'useKernel',true);
 'w/o v', struct('learnW',true,'learnZ',true,'useMemory',true,'adaptiveP',true,'useV',false,'useKernel',true);
 'w/o kernel', struct('learnW',true,'learnZ',true,'useMemory',true,'adaptiveP',true,'useV',true,'useKernel',false);
};

% -------- run --------
results = zeros(size(variants,1), 11); % [acc_mean acc_std f1_mean f1_std nmi_mean nmi_std iter_mean iter_std time_mean Wdev_mean Zdev_mean]
rowNames = cell(size(variants,1),1);

for vv=1:size(variants,1)
    name = variants{vv,1};
    cfg  = variants{vv,2};
    rowNames{vv}=name;

    acc=zeros(Restarts,1); f1=zeros(Restarts,1); nmi=zeros(Restarts,1);
    iters=zeros(Restarts,1); times=zeros(Restarts,1);
    wdev=zeros(Restarts,1); zdev=zeros(Restarts,1);

    fprintf('================ %s ================\n',name);
    for r=1:Restarts
        rng(r);
        tmp = randperm(N);
        M0 = X(tmp(1:k),:);

        tic;
        [Cluster_elem,M,EW_history,W,z] = CGFFCM_ablation_v3(X,M0,k,p_init,p_max,p_step,t_max,beta_memory,N,fuzzy_degree,d,beta_z,landa,v,G,cfg);
        times(r)=toc;
        iters(r)=numel(EW_history);
        wdev(r)=norm(W - ones(1,k)/k);
        zdev(r)=norm(z(:) - mean(z(:)));

        [~,Cluster]=max(Cluster_elem,[],1);
        EVAL = EvaluateFast(class, Cluster');
        acc(r)=EVAL(1); f1(r)=EVAL(2); nmi(r)=EVAL(3);

        fprintf('  restart %d: ACC=%.4f F1=%.4f NMI=%.4f iter=%d time=%.2fs | Wdev=%.3g Zdev=%.3g\n',r,acc(r),f1(r),nmi(r),iters(r),times(r),wdev(r),zdev(r));
    end

    results(vv,:) = [mean(acc) std(acc) mean(f1) std(f1) mean(nmi) std(nmi) mean(iters) std(iters) mean(times) mean(wdev) mean(zdev)];
end

% -------- save CSV --------
T = array2table(results,'VariableNames',{'ACC_mean','ACC_std','F1_mean','F1_std','NMI_mean','NMI_std','Iter_mean','Iter_std','Time_mean','Wdev_mean','Zdev_mean'});
T.Variant = rowNames;
T = movevars(T,'Variant','Before',1);
writetable(T,'ablation_results_113016.csv');

% -------- generate LaTeX table --------
fid = fopen('ablation_table_113016.tex','w');
fprintf(fid,'%% Auto-generated by run_ablation_113016.m\n');
fprintf(fid,'\\begin{table*}[t]\\centering\n');
fprintf(fid,'\\caption{Ablation study on image 113016. Mean$\\pm$Std over %d restarts.}\\label{tab:ablation_113016}\n',Restarts);
fprintf(fid,'\\begin{tabular}{lccc}\\toprule\n');
fprintf(fid,'Variant & ACC & F1 & NMI \\\\ \\midrule\n');
for vv=1:size(variants,1)
    fprintf(fid,'%s & %.4f$\\pm$%.4f & %.4f$\\pm$%.4f & %.4f$\\pm$%.4f \\\\\n', ...
        rowNames{vv}, results(vv,1),results(vv,2), results(vv,3),results(vv,4), results(vv,5),results(vv,6));
end
fprintf(fid,'\\bottomrule\\end{tabular}\\end{table*}\n');
fclose(fid);

fprintf('\\nSaved: ablation_results_113016.csv and ablation_table_113016.tex\\n');
